services:
  postgres:
    image: postgres:16
    container_name: donatordatabase
    restart: always

    environment:
      POSTGRES_DB: donator_db
      POSTGRES_USER: donator-user
      POSTGRES_PASSWORD: donator-secret

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: